DROP TABLE IF EXISTS metrics;
DROP TABLE IF EXISTS metrics_5m;
DROP TABLE IF EXISTS metrics_1h;
DROP TABLE IF EXISTS server_api_keys;
DROP TABLE IF EXISTS servers;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS schema_migrations;
